# Generated by Django 5.0.1 on 2024-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtype',
            name='kitchen_can_add',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypecanadd'),
        ),
        migrations.AlterField(
            model_name='cleaningtype',
            name='kitchen_include',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypeinclude'),
        ),
    ]
