# Generated by Django 5.0.1 on 2024-02-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cleaningtype_kitchen_can_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtype',
            name='kitchen_can_add',
        ),
        migrations.RemoveField(
            model_name='cleaningtype',
            name='kitchen_include',
        ),
    ]
