# Generated by Django 5.0.1 on 2024-03-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cleaningtype_kitchen_can_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTypeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Локация')),
                ('subname', models.CharField(max_length=150, verbose_name='К какому типу уборки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cleaning_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='order.cleaningtype', verbose_name='Локация уборки')),
            ],
            options={
                'verbose_name': 'Локация типа уборки',
                'verbose_name_plural': 'Локации типов уборки',
            },
        ),
        migrations.AddField(
            model_name='cleaningtypecanadd',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='can_add', to='order.cleaningtypelocation', verbose_name='Локация уборки(можно добавить)'),
        ),
        migrations.AddField(
            model_name='cleaningtypeinclude',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='include', to='order.cleaningtypelocation', verbose_name='Локация уборки(включено)'),
        ),
    ]
