# Generated by Django 5.0.1 on 2024-03-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cleaningtypelocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypecanadd',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.PROTECT, related_name='can_add', to='order.cleaningtypelocation', verbose_name='Локация уборки(можно добавить)'),
        ),
        migrations.AlterField(
            model_name='cleaningtypeinclude',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.PROTECT, related_name='include', to='order.cleaningtypelocation', verbose_name='Локация уборки(включено)'),
        ),
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
    ]
