# Generated by Django 5.0.1 on 2024-03-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cleaningtypecanadd_cleaning_type_locatiion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypecanadd',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='can_add', to='order.cleaningtypelocation', verbose_name='Локация уборки(можно добавить)'),
        ),
        migrations.AlterField(
            model_name='cleaningtypeinclude',
            name='cleaning_type_locatiion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='include', to='order.cleaningtypelocation', verbose_name='Локация уборки(включено)'),
        ),
    ]
