# Generated by Django 5.0.1 on 2024-03-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cleaningtypecanadd_cleaning_type_locatiion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
    ]
