# Generated by Django 5.0.1 on 2024-03-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_cleaningtypelocation_cleaning_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
    ]
